### ISSUE TITLE
ERROR: device didn't accept BasebandData

### ISSUE THREAD

**Issue by daniel-bluesea** [libimobiledevice/idevicerestore#138]
it occurs every now and then, what could be the problem?

more relevant log lines:
About to send BasebandData...
Sending BasebandData now...
Done sending BasebandData
Updating baseband (19)
Updating baseband (19)
Updating baseband (19)
Updating baseband (19)
Got status message
Status: Verification Error

btw, it seems that **plist_dict_set_item(opts, "UpdateBaseband", plist_new_bool(0));** doesn't have any affect

**Comment by daniel-bluesea** [comment]
is it possible to add some kind of retry mechanism?

**Comment by nikias** [comment]
The setting of UpdateBaseband to false doesn't work because all production devices ignore the restore options and only use defaults predefined in the restore ramdisk.
Why the baseband update might have failed I can't tell... adding a retry doesn't work because the device controls the restore process.
