### ISSUE TITLE
DEVICE WITH NAND-CHIP ISSUE IS STUCK AT "FIRMWARE FLASHING" 

### ISSUE THREAD

**Issue by Dantee296** [libimobiledevice/idevicerestore#192]
its stuck at  "FIRMWARE FLASHING" 
want to atleast tell if fail or pass it stuck there

@nikias  what to do where to change to know that it has a nand chip issue and firmware flashing wont work ?

need to add timeout ?
Please Help @nikias

**Comment by Dantee296** [comment]
@nikias ??

**Comment by nikias** [comment]
This is not enough information to comment on it. If it is "stuck" on that step ("Flashing Firmware" I suppose) then idevicerestore is waiting for feedback from the device. Nothing much we can do here since the actual restore process is handled by the device itself. As you mentioned NAND-chip issue this is probably the reason it will not succeed.

**Comment by Dantee296** [comment]
ok Thanks
