### ISSUE TITLE
Installation on Arch Linux

### ISSUE THREAD

**Issue by devraza** [libimobiledevice/idevicerestore#427]
Hi, I'm using Arch Linux and would like to know how to install idevicerestore on my system, since the README only provides information on installation for Debian/Ubuntu based distributions (with apt as a package manager).

**Comment by nikias** [comment]
You want to build it yourself, from source, since whatever packaged version is out there will pretty likely be outdated anyway. In that case you need to follow general linux build instructions.

I have this script, but it's for Debian-bases distributions (also Ubuntu):
https://gist.github.com/nikias/e72902570cca679e752a7076a6b2127e

The steps will be similar, but you need to figure out how to install the tools and development packages (see line 3).
